### PR TITLE
Added custom styles into notification inframes

### PR DESCRIPTION
**Pull request by guidiego**
First of all, thx for the awesome lib :)

I need to customized the notification box, so I edit a little parts of code to add custom style in `notification frame`. Let me know if I need change something more!

### CODE REVIEW

**Comment by JacobMarshallPP** [comment]
Thanks for your contribution, @guidiego!

Looks like a simple enough change, but we'll make sure that it's tested before we merge it in 🙂

**Comment by guidiego** [comment]
@JacobMarshallPP yeah! I'm testing here too :D Let me ask, do you have any problem when you run the lib local? In my online environment my master run perfectly, but when I install the git repository by NPM that not inject styles for me. Any ideia?

**Comment by JacobMarshallPP** [comment]
> @JacobMarshallPP yeah! I'm testing here too :D Let me ask, do you have any problem when you run the lib local? In my online environment my master run perfectly, but when I install the git repository by NPM that not inject styles for me. Any ideia?

Not entirely sure, that does sound rather strange. Do you get any errors while installing the module, or during runtime?

**Comment by guidiego** [comment]
> Not entirely sure, that does sound rather strange. Do you get any errors while installing the module, or during runtime?

The both environments not give me exceptions, this is the more strange.

**Comment by JacobMarshallPP** [comment]
> The both environments not give me exceptions, this is the more strange.

I will try and replicate, and open an issue if there's any problem there.

**Comment by JacobMarshallPP** [comment]
Looking great, thanks again @guidiego. Tested perfectly!

**Pull request merged**
